### ISSUE TITLE
{'code': '4', 'message': '今日校园版本过低，请更新至最新版本！'}

### ISSUE THREAD

**Issue by kangkang54** [NekoRectifier/NoTeenStudy#2]
加了  form['uaIsCpadaily']=True 之后 提示{'code': '4', 'message': '今日校园版本过低，请更新至最新版本！'}，
不加 form['uaIsCpadaily']=True，提示{'code': '2210010000', 'message': '请提交正确的签到信息'}

**Comment by NekoRectifier** [comment]
推测您的config.yml可能修改了某些导致其无法工作的配置? 介意将config.yml的内容脱敏后发上来吗?
